Update the code to not generate compressed CSV files, changed the field length of few tables

diff --git a/sql/ght-restore-pg b/sql/ght-restore-pg
--- a/sql/ght-restore-pg
+++ b/sql/ght-restore-pg
@@ -55,52 +55,43 @@ fi
 # Convert to full path
 dumpDir="`pwd`/$dumpDir"
 
-pgDir=`echo $dumpDir/pg_scipts`
-
-if [ ! -e $pgDir/schema.sql ]; then
-  echo "Cannot find $pgDir/schema.sql to create DB schema"
+if [ ! -e $dumpDir/pg_schema.sql ]; then
+  echo "Cannot find $dumpDir/pg_schema.sql to create DB schema"
   exit 1
 fi
 
 # 1. Create db schema
 echo "`date` Creating the DB schema"
-cat $pgDir/schema.sql | $psql
-
-count=`ls -1 $dumpDir/*.csv | wc -l`
-if [ $count != 0 ]; then
-   for f in $dumpDir/*.csv ; do
-     gzip $f
-   done
-fi
+cat $dumpDir/pg_schema.sql | $psql
 
 # 2. Restore CSV files with disabled FK checks
-for f in $dumpDir/*.csv.gz ; do
+for f in $dumpDir/*.csv ; do
   table=`basename $f|cut -f1 -d'.'`
   echo "`date` Restoring table $table"
-  echo "COPY $table FROM PROGRAM 'zcat < $f' WITH (FORMAT 'csv', QUOTE E'\"', ESCAPE '\', NULL '\N');" | $psql || exit 1
+  echo "COPY $table FROM '$f' WITH (FORMAT 'csv', QUOTE E'\"', ESCAPE '\', NULL '\N');" | $psql || exit 1
 done
 
 # 3. Reset sequences
-if [ ! -e $pgDir/reset_sequences.sql ]; then
-  echo "Cannot find $pgDir/reset_sequences.sql to create DB indexes and foreign keys"
+if [ ! -e $dumpDir/pg_reset_sequences.sql ]; then
+  echo "Cannot find $dumpDir/pg_reset_sequences.sql to create DB indexes and foreign keys"
   exit 1
 fi
 
 echo "`date` Resetting sequences"
-cat $pgDir/reset_sequences.sql |
+cat $dumpDir/pg_reset_sequences.sql |
 while read idx; do
   echo "`date` $idx"
   echo $idx | $psql || exit 1
 done
 
 # 4. Create indexes
-if [ ! -e $pgDir/indexes_and_foreign_keys.sql ]; then
-  echo "Cannot find $pgDir/indexes_and_foreign_keys.sql to create DB indexes and foreign keys"
+if [ ! -e $dumpDir/pg_indexes_and_foreign_keys.sql ]; then
+  echo "Cannot find $dumpDir/pg_indexes_and_foreign_keys.sql to create DB indexes and foreign keys"
   exit 1
 fi
 
 echo "`date` Creating indexes"
-cat $pgDir/indexes_and_foreign_keys.sql |
+cat $dumpDir/pg_indexes_and_foreign_keys.sql |
 while read idx; do
   echo "`date` $idx"
   echo $idx | $psql || exit 1
