Revert the changes in mysql scripts and update the ght-dump-pg script to generate MySQL compatible CSV files

diff --git a/sql/ght-restore-mysql b/sql/ght-restore-mysql
--- a/sql/ght-restore-mysql
+++ b/sql/ght-restore-mysql
@@ -5,6 +5,7 @@ user="ghtorrent"
 passwd=""
 host="localhost"
 db="ghtorrent"
+engine="MyISAM"
 
 usage()
 {
@@ -15,6 +16,8 @@ usage()
   echo "    -p database passwd (default: $passwd)"
   echo "    -h database host (default: $host)"
   echo "    -d database to restore to. Must exist. (default: $db)"
+  echo "    -e db engine: MyISAM for fast import and querying speed"
+  echo "                  InnoDB for normal operations (default: $engine)"
 }
 
 if [ -z $1 ]
@@ -23,13 +26,14 @@ then
   exit 1
 fi
 
-while getopts "u:p:h:d:" o
+while getopts "u:p:h:d:e:" o
 do
   case $o in
   u)  user=$OPTARG ;;
   p)  passwd=$OPTARG ;;
   h)  host=$OPTARG ;;
   d)  db=$OPTARG ;;
+  e)  engine=$OPTARG ;;
   \?)     echo "Invalid option: -$OPTARG" >&2
     usage
     exit 1
@@ -37,12 +41,12 @@ do
   esac
 done
 
-# Setup PostgreSQL command line
-if ! [ -z $passwd ]; then
-  export PGPASSWORD=$passwd
+# Setup MySQL command line
+if [ -z $passwd ]; then
+  mysql="mysql -u $user -s -h $host -D $db"
+else
+  mysql="mysql -u $user --password=$passwd -s -h $host -D $db"
 fi
-
-psql="psql -U $user -t -q -h $host -d $db"
 
 shift $(expr $OPTIND - 1)
 dumpDir=$1
@@ -62,26 +66,39 @@ fi
 
 # 1. Create db schema
 echo "`date` Creating the DB schema"
-cat $dumpDir/schema.sql | $psql
+cat $dumpDir/schema.sql |
+sed -e "s/\`ghtorrent\`/\`$db\`/" |
+sed -e "s/InnoDB/$engine/"|
+grep -v "^--" |
+$mysql
+
+count=`ls -1 $dumpDir/*.csv.gz | wc -l`
+if [ $count != 0 ]; then
+   for f in $dumpDir/*.csv.gz ; do
+     gunzip $f
+   done
+fi
 
 # 2. Restore CSV files with disabled FK checks
-for f in $dumpDir/*.csv.gz ; do
+for f in $dumpDir/*.csv ; do
   table=`basename $f|cut -f1 -d'.'`
   echo "`date` Restoring table $table"
-  echo "COPY $table FROM PROGRAM 'zcat < $f';" | $psql || exit 1
+  echo "SET foreign_key_checks = 0; LOAD DATA LOCAL INFILE '$f' INTO TABLE $table CHARACTER SET UTF8 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n';" |$mysql || exit 1
 done
 
 # 3. Create indexes
-if [ ! -e $dumpDir/indexes_and_foreign_keys.sql ]; then
-  echo "Cannot find $dumpDir/indexes_and_foreign_keys.sql to create DB indexes and foreign keys"
+if [ ! -e $dumpDir/indexes.sql ]; then
+  echo "Cannot find $dumpDir/indexes.sql to create DB indexes"
   exit 1
 fi
 
 echo "`date` Creating indexes"
-cat $dumpDir/indexes_and_foreign_keys.sql |
+cat $dumpDir/indexes.sql |
+sed -e "s/\`ghtorrent\`/\`$db\`/" |
+grep -v "^--" |
 while read idx; do
   echo "`date` $idx"
-  echo $idx | $psql || exit 1
+  echo $idx | $mysql || exit 1
 done
 
 #: ft=bash
